### ISSUE TITLE
plugin.json issues

### ISSUE THREAD

**Issue by cschol** [max-circlefade/Circlefade#3]
The plugin manifest validator found the following issues:

```
Validating Circlefade
Invalid URL: www.circlefade.com/vcv
Invalid URL: www.circlefade.com
Invalid URL: www.circlefade.com/vcv
```

Please use the **https://** prefix for URLs.

**Comment by max-circlefade** [comment]
Woops was building fine on my mac, error corrected :)
New commit: 238e2e4e03fbe58a1d8ae659947b5fd36fd9a517

**Comment by cschol** [comment]
Thanks. It's not a build-time error. This is a validation script run by me on the `plugin.json` during integration.
